<a href="https://colab.research.google.com/github/rakeshbanisetti/mds_lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Connecting to GitHub Repository

I will now clone the GitHub repository `https://github.com/rakeshbanisetti/mds_lab.git` into your Colab environment. This will download all the files from the repository into a folder named `mds_lab` in your current working directory.

In [ ]:
!git clone https://github.com/rakeshbanisetti/mds_lab.git

Cloning into 'mds_lab'...


In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [1]:
import numpy
l1=[55,2,3,4,5]
l2=[55,7,8,9,10]
aar_1=numpy.array(l1)
aar_2=numpy.array(l2)
print(aar_1)
print(aar_2)
print(aar_1+aar_2)
print(aar_1*aar_2)
print(aar_1-aar_2)
print(aar_1/aar_2)

[55  2  3  4  5]
[55  7  8  9 10]
[110   9  11  13  15]
[3025   14   24   36   50]
[ 0 -5 -5 -5 -5]
[1.         0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
# List the contents of the cloned repository directory
!ls mds_lab

In [2]:
l1=[55,2,3,4,5]

In [ ]:
import time

# Define the size of the list to be created
list_size = 1000000

start_time = time.time()
my_list = list(range(list_size))
end_time = time.time()

time_taken = end_time - start_time
print(f"Time taken to create a list of {list_size} elements: {time_taken:.6f} seconds")

Time taken to create a list of 1000000 elements: 0.020610 seconds


In [ ]:
import time
import numpy as np

# Define the size of the array to be created (same as the list)
array_size = 1000000

start_time_np = time.time()
my_numpy_array = np.arange(array_size)
end_time_np = time.time()

time_taken_np = end_time_np - start_time_np
print(f"Time taken to create a NumPy array of {array_size} elements: {time_taken_np:.6f} seconds")

Time taken to create a NumPy array of 1000000 elements: 0.003017 seconds


### Comparing Basic Operations: Python Lists vs. NumPy Arrays

Now, let's compare the time taken for common arithmetic operations (addition, subtraction, multiplication, and division) using both standard Python lists and NumPy arrays. We will use a large number of elements to clearly see the performance differences.

In [ ]:
import time
import numpy as np

operation_size = 1000000 # Using the same size for consistency

# --- Python List Operations ---
python_list_1 = list(range(operation_size))
python_list_2 = list(range(operation_size, operation_size * 2))

print(f"\n--- Python List Operations (on {operation_size} elements) ---")

# List Addition
start_time = time.time()
python_list_add = [python_list_1[i] + python_list_2[i] for i in range(operation_size)]
end_time = time.time()
time_taken_list_add = end_time - start_time
print(f"Time for List Addition: {time_taken_list_add:.6f} seconds")

# List Subtraction
start_time = time.time()
python_list_sub = [python_list_1[i] - python_list_2[i] for i in range(operation_size)]
end_time = time.time()
time_taken_list_sub = end_time - start_time
print(f"Time for List Subtraction: {time_taken_list_sub:.6f} seconds")

# List Multiplication
start_time = time.time()
python_list_mul = [python_list_1[i] * python_list_2[i] for i in range(operation_size)]
end_time = time.time()
time_taken_list_mul = end_time - start_time
print(f"Time for List Multiplication: {time_taken_list_mul:.6f} seconds")

# List Division
# Avoid ZeroDivisionError for division, add 1 to list_2 to ensure non-zero denominators
python_list_2_div = list(range(operation_size, operation_size * 2))
start_time = time.time()
python_list_div = [python_list_1[i] / (python_list_2_div[i] if python_list_2_div[i] != 0 else 1) for i in range(operation_size)]
end_time = time.time()
time_taken_list_div = end_time - start_time
print(f"Time for List Division: {time_taken_list_div:.6f} seconds")


--- Python List Operations (on 1000000 elements) ---
Time for List Addition: 0.071950 seconds
Time for List Subtraction: 0.068927 seconds
Time for List Multiplication: 0.078928 seconds
Time for List Division: 0.102904 seconds


In [ ]:
import time
import numpy as np

operation_size = 1000000 # Using the same size for consistency

# --- NumPy Array Operations ---
numpy_array_1 = np.arange(operation_size)
numpy_array_2 = np.arange(operation_size, operation_size * 2)

print(f"\n--- NumPy Array Operations (on {operation_size} elements) ---")

# NumPy Array Addition
start_time = time.time()
numpy_array_add = numpy_array_1 + numpy_array_2
end_time = time.time()
time_taken_np_add = end_time - start_time
print(f"Time for NumPy Array Addition: {time_taken_np_add:.6f} seconds")

# NumPy Array Subtraction
start_time = time.time()
numpy_array_sub = numpy_array_1 - numpy_array_2
end_time = time.time()
time_taken_np_sub = end_time - start_time
print(f"Time for NumPy Array Subtraction: {time_taken_np_sub:.6f} seconds")

# NumPy Array Multiplication
start_time = time.time()
numpy_array_mul = numpy_array_1 * numpy_array_2
end_time = time.time()
time_taken_np_mul = end_time - start_time
print(f"Time for NumPy Array Multiplication: {time_taken_np_mul:.6f} seconds")

# NumPy Array Division
# Avoid ZeroDivisionError, ensure non-zero denominators
numpy_array_2_div = np.arange(operation_size, operation_size * 2)
# Replace zeros in array_2_div with a non-zero value if any, though arange won't have zeros here
# For robustness, we could add a small epsilon or check for zeros if the data source was different.
start_time = time.time()
numpy_array_div = numpy_array_1 / numpy_array_2_div
end_time = time.time()
time_taken_np_div = end_time - start_time
print(f"Time for NumPy Array Division: {time_taken_np_div:.6f} seconds")


--- NumPy Array Operations (on 1000000 elements) ---
Time for NumPy Array Addition: 0.003023 seconds
Time for NumPy Array Subtraction: 0.003488 seconds
Time for NumPy Array Multiplication: 0.003335 seconds
Time for NumPy Array Division: 0.004287 seconds


The output of the previous cells demonstrates the significant performance improvement that NumPy arrays offer over standard Python lists for element-wise arithmetic operations, especially with a large number of elements. This is due to NumPy's optimized C implementations for these operations.

### Comparing Operations on Small Lists (`l1`, `l2`)

In [ ]:
import time
import numpy as np

# Assuming l1 and l2 are already defined as [1,2,3,4,5] and [6,7,8,9,10]
# Convert them to numpy arrays for comparison
numpy_arr_l1 = np.array(l1)
numpy_arr_l2 = np.array(l2)

print("--- Python List Operations (l1, l2) ---")

# List Addition
start_time = time.time()
list_add_result = [l1[i] + l2[i] for i in range(len(l1))]
end_time = time.time()
time_taken_list_add_small = end_time - start_time
print(f"Time for List Addition: {time_taken_list_add_small:.9f} seconds")

# List Subtraction
start_time = time.time()
list_sub_result = [l1[i] - l2[i] for i in range(len(l1))]
end_time = time.time()
time_taken_list_sub_small = end_time - start_time
print(f"Time for List Subtraction: {time_taken_list_sub_small:.9f} seconds")

# List Multiplication
start_time = time.time()
list_mul_result = [l1[i] * l2[i] for i in range(len(l1))]
end_time = time.time()
time_taken_list_mul_small = end_time - start_time
print(f"Time for List Multiplication: {time_taken_list_mul_small:.9f} seconds")

# List Division
start_time = time.time()
list_div_result = [l1[i] / l2[i] for i in range(len(l1))]
end_time = time.time()
time_taken_list_div_small = end_time - start_time
print(f"Time for List Division: {time_taken_list_div_small:.9f} seconds")

--- Python List Operations (l1, l2) ---
Time for List Addition: 0.000095844 seconds
Time for List Subtraction: 0.000076771 seconds
Time for List Multiplication: 0.000069857 seconds
Time for List Division: 0.000069380 seconds


In [ ]:
import time
import numpy as np

# Assuming numpy_arr_l1 and numpy_arr_l2 are already defined

print("\n--- NumPy Array Operations (numpy_arr_l1, numpy_arr_l2) ---")

# NumPy Array Addition
start_time = time.time()
numpy_add_result = numpy_arr_l1 + numpy_arr_l2
end_time = time.time()
time_taken_np_add_small = end_time - start_time
print(f"Time for NumPy Array Addition: {time_taken_np_add_small:.9f} seconds")

# NumPy Array Subtraction
start_time = time.time()
numpy_sub_result = numpy_arr_l1 - numpy_arr_l2
end_time = time.time()
time_taken_np_sub_small = end_time - start_time
print(f"Time for NumPy Array Subtraction: {time_taken_np_sub_small:.9f} seconds")

# NumPy Array Multiplication
start_time = time.time()
numpy_mul_result = numpy_arr_l1 * numpy_arr_l2
end_time = time.time()
time_taken_np_mul_small = end_time - start_time
print(f"Time for NumPy Array Multiplication: {time_taken_np_mul_small:.9f} seconds")

# NumPy Array Division
start_time = time.time()
numpy_div_result = numpy_arr_l1 / numpy_arr_l2
end_time = time.time()
time_taken_np_div_small = end_time - start_time
print(f"Time for NumPy Array Division: {time_taken_np_div_small:.9f} seconds")


--- NumPy Array Operations (numpy_arr_l1, numpy_arr_l2) ---
Time for NumPy Array Addition: 0.000084877 seconds
Time for NumPy Array Subtraction: 0.000051737 seconds
Time for NumPy Array Multiplication: 0.000046015 seconds
Time for NumPy Array Division: 0.000054359 seconds


In [4]:
matrix=np.array([[55,2],[3,4]])

As you can observe from the output, for very small lists like `l1` and `l2` (with only 5 elements), the time differences between Python list operations and NumPy array operations are minimal, and sometimes Python lists might even appear faster due to the overhead of creating and managing NumPy arrays. NumPy's true performance advantage becomes evident when working with much larger datasets, as demonstrated in the previous comparison with 1,000,000 elements.

### Using `%%timeit` for Micro-benchmarking

The `%%timeit` magic command (available in Jupyter and Colab notebooks) is used to measure the execution time of a single statement or an entire cell. It automatically runs the code multiple times (typically 100,000 to 10,000,000 times for fast code) and calculates the average execution time, providing a more reliable measurement for small operations.

Let's use `%%timeit` to compare the basic operations on our small lists `l1` and `l2` and their NumPy array equivalents.

In [3]:
import numpy as np

l1 = [55,2,3,4,5]
l2 = [55,7,8,9,10]

numpy_arr_l1 = np.array(l1)
numpy_arr_l2 = np.array(l2)

--- Python List Operations (using `%%timeit`) ---

In [ ]:
%%timeit [l1[i] + l2[i] for i in range(len(l1))]

ValueError: empty body on For

In [ ]:
%%timeit [l1[i] - l2[i] for i in range(len(l1))]

ValueError: empty body on For

In [ ]:
%%timeit [l1[i] * l2[i] for i in range(len(l1))]

ValueError: empty body on For

In [ ]:
%%timeit [l1[i] / l2[i] for i in range(len(l1))]

ValueError: empty body on For

--- NumPy Array Operations (using `%%timeit`) ---

In [ ]:
%%timeit numpy_arr_l1 + numpy_arr_l2

ValueError: empty body on For

In [ ]:
%%timeit numpy_arr_l1 - numpy_arr_l2

ValueError: empty body on For

In [ ]:
%%timeit numpy_arr_l1 * numpy_arr_l2

ValueError: empty body on For

In [ ]:
%%timeit numpy_arr_l1 / numpy_arr_l2

ValueError: empty body on For

In [5]:
import numpy as np
matrix=np.array([[55,2],[3,4]])
print(matrix)

[[55  2]
 [ 3  4]]


In [ ]:
matrix.dtype

dtype('int64')

In [6]:
m=np.zeros([3,3])
m[0,0] = 55
print(m)

[[55.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
n=np.ones([3,3])
n[0,0] = 55
print(n)

[[55.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


### Creating a Matrix with All Same Elements

YouYou can use `np.full()` to create an array of a given shape and fill it with a specific value. Alternatively, you can create an array of zeros or ones and then multiply it by the desired scalar.

In [8]:
import numpy as np

matrix_full = np.full((3, 3), 7)
matrix_full[0,0] = 55
print("Matrix using np.full():")
print(matrix_full)

matrix_zeros_multiplied = np.zeros((2, 4)) * 5
matrix_zeros_multiplied[0,0] = 55
print("\nMatrix using np.zeros() and multiplication:")
print(matrix_zeros_multiplied)

matrix_ones_multiplied = np.ones((4, 2)) * 10
matrix_ones_multiplied[0,0] = 55
print("\nMatrix using np.ones() and multiplication:")
print(matrix_ones_multiplied)

Matrix using np.full():
[[55  7  7]
 [ 7  7  7]
 [ 7  7  7]]

Matrix using np.zeros() and multiplication:
[[55.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

Matrix using np.ones() and multiplication:
[[55. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


The repository should now be cloned. You can verify this by checking the file explorer in Colab or by running `!ls` in a new cell.

### Creating an Identity Matrix

An identity matrix is a square matrix where all the elements on the main diagonal are ones, and all other elements are zeros. It is denoted by $I_n$, where $n$ is the dimension of the square matrix. In NumPy, you can create an identity matrix using the `np.eye()` function.

In [9]:
import numpy as np

identity_matrix_3x3 = np.eye(3)
identity_matrix_3x3[0,0] = 55
print("3x3 Identity Matrix:")
print(identity_matrix_3x3)

identity_matrix_4x4 = np.eye(4)
identity_matrix_4x4[0,0] = 55
print("\n4x4 Identity Matrix:")
print(identity_matrix_4x4)

identity_matrix_float = np.eye(2, dtype=float)
identity_matrix_float[0,0] = 55
print("\n2x2 Identity Matrix with float type:")
print(identity_matrix_float)

3x3 Identity Matrix:
[[55.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

4x4 Identity Matrix:
[[55.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

2x2 Identity Matrix with float type:
[[55.  0.]
 [ 0.  1.]]


### Creating a Diagonal Matrix with Specific Values

To create a matrix where the diagonal elements are a specific value (e.g., 5) and all other elements are zero, you can simply multiply an identity matrix by that scalar value. An identity matrix has ones on the diagonal, so scaling it will place the desired value on the diagonal.

In [10]:
import numpy as np
diagonal_matrix_5 = np.eye(3) * 5
diagonal_matrix_5[0,0] = 55
print("3x3 Matrix with 5s on the diagonal:")
print(diagonal_matrix_5)
diagonal_matrix_10 = np.eye(4) * 10
diagonal_matrix_10[0,0] = 55
print("\n4x4 Matrix with 10s on the diagonal:")
print(diagonal_matrix_10)

3x3 Matrix with 5s on the diagonal:
[[55.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  5.]]

4x4 Matrix with 10s on the diagonal:
[[55.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]


In [ ]:
!ls

mds_lab  sample_data
